# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Progress.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Progress(object):
    def setupUi(self, Progress):
        Progress.setObjectName("Progress")
        Progress.resize(400, 157)
        self.gridLayout = QtWidgets.QGridLayout(Progress)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Progress)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.statusLabel = QtWidgets.QLabel(Progress)
        font = QtGui.QFont()
        font.setBold(True)
        self.statusLabel.setFont(font)
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout_3.addWidget(self.statusLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Progress)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.videoProgressBar = QtWidgets.QProgressBar(Progress)
        self.videoProgressBar.setProperty("value", 0)
        self.videoProgressBar.setObjectName("videoProgressBar")
        self.horizontalLayout.addWidget(self.videoProgressBar)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.CancelButton = QtWidgets.QPushButton(Progress)
        self.CancelButton.setEnabled(False)
        self.CancelButton.setObjectName("CancelButton")
        self.horizontalLayout_2.addWidget(self.CancelButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(Progress)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.audioProgressBar = QtWidgets.QProgressBar(Progress)
        self.audioProgressBar.setProperty("value", 0)
        self.audioProgressBar.setObjectName("audioProgressBar")
        self.horizontalLayout_5.addWidget(self.audioProgressBar)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)

        self.retranslateUi(Progress)
        QtCore.QMetaObject.connectSlotsByName(Progress)

    def retranslateUi(self, Progress):
        _translate = QtCore.QCoreApplication.translate
        Progress.setWindowTitle(_translate("Progress", "下载进度"))
        self.label_2.setText(_translate("Progress", "状态："))
        self.statusLabel.setText(_translate("Progress", "正在初始化..."))
        self.label.setText(_translate("Progress", "视频下载进度"))
        self.CancelButton.setText(_translate("Progress", "取消"))
        self.label_3.setText(_translate("Progress", "音频下载进度"))
